### ISSUE TITLE
Permissions hook generates fatal error in logged out state

### ISSUE THREAD

**Issue by beck24** [ColdTrick/user_support#16]
PHP Fatal error:  Call to a member function getGUID() on a non-object in /var/www/html/elgg/docroot/mod/user_support/lib/hooks.php on line 365

When logged out, if this hook fires a fatal error is generated as the user entity is assumed.  This is an invalid assumption for a permissions check.
Need to add a check for a valid user entity.

**Comment by jdalsem** [comment]
This has been resolved... somewhere in the past
