### ISSUE TITLE
notifications not being send

### ISSUE THREAD

**Issue by jeabakker** [ColdTrick/user_support#18]
You have a new comment on your item "User Support" from clu55ter. It reads:

I’m testing out user support on elgg 1.9 from
https://github.com/ColdTrick/user_support but for some reason no support
tickets notifications being received, the site definatley sends out other
notifications such as messages and mentions etc.. Could this have anything
to do with the fact that I’m using phpmailer plugin?

**Comment by jdalsem** [comment]
unable to reproduce
