### ISSUE TITLE
icons not showing up in listing

### ISSUE THREAD

**Issue by jeabakker** [ColdTrick/user_support#20]
@clu55ter reported https://github.com/ColdTrick/user_support/issues/19#issuecomment-72644280:

> Just noticed that the above bug fix has done something funny with the way that the tickets are displayed on the support tickets url www.mysite.co.uk/user_support/support_ticket.
Please see below image to give you an idea of what I mean.
https://www.flickr.com/photos/96808391@N07/16248493709/

**Comment by jeabakker** [comment]
it looks like the icons can't be loaded and thus you see the alt text instead of the icon.

if you look in the sourcecode of the page the src of the image should be http://yourdomain.com/mod/user_support/_graphics/faq/tiny.png (instead of faq it can also say question/bug/request)

if that is the url check if you can access it in your browser.
the images are located in the folder/mod/user_support/_graphics/faq/tiny.png you can check if the images exists

**Comment by clu55ter** [comment]
Hi Jerome! I've just taken another look at this and have realized that I had forgotten to rename user_support_master to user_support, once I renamed the mod and done an upgrade icons are now displaying properly.

Thanks for your help!
