### ISSUE TITLE
"user_support/support_ticket/add" shows in contextual help dropdown

### ISSUE THREAD

**Issue by javery86** [ColdTrick/user_support#29]
If you have support tickets open and you're viewing all FAQ items, then click on "Read more" for one of the FAQ, you'll see "user_support/support_ticket/add" is showing in the "Contextual help" dropdown field.

**Comment by jeabakker** [comment]
I'm unclear about what you mean

- goto FAQs (/user_support/faq)
- goto a FAQ (/user_support/faq/view/<some number>)
- and then??

**Comment by javery86** [comment]
I hope this screenshot helps...


Joseph Avery, MSc, ACSM-RCEP

Phone: (808) 853-0675
Email: j.avery@msn.com<mailto:j.avery@msn.com>

________________________________

**Comment by jeabakker** [comment]
FAQ apply to one or more 'sections' these sections are what we call 'contextual help'. So the FAQ you're creating in the screenshot will be shown in the help center when a user is on the 'create support ticket' page.

If you create more help pages this list will become larger. For now it's not yet possible to add contextual help sections manually.

**Comment by jeabakker** [comment]
Maybe we should explain what that field does, so it's less confusing

**Comment by javery86** [comment]
Yes, that would be a good idea. :)
