### ISSUE TITLE
Make sure the support tickets ACL's have a subtype

### ISSUE THREAD

**Issue by jeabakker** [ColdTrick/user_support#36]
**Elgg version**
Which version of Elgg are you using

**Plugin version**
Which version of the plugin are you using

**Plugin source**
- Elgg community page download
- Git clone (did you run `composer install`?)
- Composer installation
- Github releases download

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/user_support/commit/312bb55804e8481f0c9a7b6ffa7451aa2ff0bcbb#diff-64fc045898c96c86bd7e2ffbb496f91238a16e813a5af12395c3afe24878079f
